<?php 

$req = "CREATE TABLE type (
  IDTYPE int IDENTITY,
  NOMTYPE varchar(20) NOT NULL,
  ARRETBAIL int NOT NULL,
  DUREEPREAVIS int NOT NULL,
  PRIMARY KEY (IDTYPE)
);"; 

 $req = "CREATE TABLE departement (
  IDDEP int NOT NULL,
  NOMDEP varchar(40) NOT NULL,
  PRIMARY KEY (IDDEP)
);"; 

$req = "CREATE TABLE ville (
  IDVILLE int IDENTITY,
  IDDEP int NOT NULL,
  NOMVILLE varchar(40) NOT NULL,
  PRIMARY KEY (IDVILLE),
  FOREIGN KEY (IDDEP) REFERENCES departement(IDDEP)
);"; 



$req = "CREATE TABLE adresse (
  IDADRESSE int IDENTITY,
  IDVILLE int NOT NULL,
  NUMRUE int NOT NULL,
  NOMRUE varchar(70) NOT NULL,
  PRIMARY KEY (IDADRESSE),
  FOREIGN KEY (IDVILLE) REFERENCES ville(IDVILLE)
)"; 

 $req = "CREATE TABLE loyer (
  IDLOYER int IDENTITY,
  MONTANT float NOT NULL,
  ANNEE int NOT NULL,
  PRIMARY KEY (IDLOYER)
);"; 

 $req = "CREATE TABLE plage (
  IDPLAGE int NOT NULL,
  PLAGE varchar(20) NOT NULL,
  PRIMARY KEY (IDPLAGE)
)"; 

$req = "CREATE TABLE utilisateur (
  IDUTILISATEUR int IDENTITY,
  IDADRESSE int NOT NULL,
  NOM varchar(30) NOT NULL,
  PRENOM varchar(30) NOT NULL,
  MAIL varchar(80) DEFAULT NULL,
  TEL int DEFAULT NULL,
  PASSWORD varchar(50) NOT NULL,
  ESTOUVERT tinyint DEFAULT 1,
  IDSYSUSER int NOT NULL,
  PRIMARY KEY (IDUTILISATEUR),
  FOREIGN KEY (IDADRESSE) REFERENCES adresse(IDADRESSE)
);"; 

 $req = "CREATE TABLE appartement (
  IDAPPARTEMENT int IDENTITY,
  IDTYPE int NOT NULL,
  IDLOYER int NOT NULL,
  IDUTILISATEUR int NOT NULL,
  IDADRESSE int NOT NULL,
  NUMAPPARTEMENT int NOT NULL,
  SURFACE int NOT NULL,
  ESTDISPONIBLE tinyint DEFAULT 1,
  URLPHOTO text DEFAULT NULL,
  PRIMARY KEY (IDAPPARTEMENT),
  FOREIGN KEY (IDUTILISATEUR) REFERENCES utilisateur(IDUTILISATEUR),
  FOREIGN KEY (IDLOYER) REFERENCES loyer(IDLOYER),
  FOREIGN KEY (IDTYPE) REFERENCES type(IDTYPE),
  FOREIGN KEY (IDADRESSE) REFERENCES adresse(IDADRESSE)
);"; 

$req = "CREATE TABLE description (
  IDDESCRIPTION int IDENTITY,
  IDAPPARTEMENT int NOT NULL,
  NOMDESCRIPTION varchar(30) NOT NULL,
  VAL text DEFAULT NULL,
  PRIMARY KEY (IDDESCRIPTION),
  FOREIGN KEY (IDAPPARTEMENT) REFERENCES appartement(IDAPPARTEMENT)
);"; 



 $req = "CREATE TABLE contratlocation (
  IDCONTRAT int IDENTITY,
  IDUTILISATEUR int NOT NULL,
  IDAPPARTEMENT int NOT NULL,
  DATEDEBUTLOC date NOT NULL,
  DATEFINLOC date DEFAULT NULL,
  PRIMARY KEY (IDCONTRAT),
  FOREIGN KEY (IDUTILISATEUR) REFERENCES utilisateur(IDUTILISATEUR),
  FOREIGN KEY (IDAPPARTEMENT) REFERENCES appartement(IDAPPARTEMENT)
);"; 

$req = "CREATE TABLE statistiques (
  IDSTAT int IDENTITY,
  NOMSTAT varchar(20),
  VALEURSTAT int,
  UNITE varchar(10)
);";

 $req = "CREATE TABLE paiement (
  IDPAIEMENT int IDENTITY,
  IDCONTRAT int NOT NULL,
  IDPLAGE int NOT NULL,
  DATEPAIEMENT date NULL,
  PRIMARY KEY (IDPAIEMENT),
  FOREIGN KEY (IDPLAGE) REFERENCES plage(IDPLAGE),
  FOREIGN KEY (IDCONTRAT) REFERENCES contratlocation(IDCONTRAT)
);"; 

$req = "CREATE TABLE archivecontrat (
  IDCONTTRATARCHIVE int IDENTITY,
  IDUTILISATEUR int NOT NULL,
  IDAPPARTEMENT int NOT NULL,
  ARCHIVEDATEDEBUT date NOT NULL,
  ARCHIVEDATEFIN date NOT NULL,
  PRIMARY KEY (IDCONTTRATARCHIVE),
  FOREIGN KEY (IDUTILISATEUR) REFERENCES utilisateur(IDUTILISATEUR),
  FOREIGN KEY (IDAPPARTEMENT) REFERENCES appartement(IDAPPARTEMENT)
);"; 


/* INSERTION */

$req = "INSERT INTO departement (IDDEP, NOMDEP) VALUES
(54, 'MEURTHE ET MOSELLE');INSERT INTO departement (IDDEP, NOMDEP) VALUES
(57, 'MOSELLE');INSERT INTO departement (IDDEP, NOMDEP) VALUES
(88, 'VOSGES'); 
"; 

$req = "INSERT INTO ville (NOMVILLE,IDDEP) VALUES
('Nancy', 54); INSERT INTO ville (NOMVILLE,IDDEP) VALUES
('Lunéville', 54); INSERT INTO ville (NOMVILLE,IDDEP) VALUES
('Metz', 57); INSERT INTO ville (NOMVILLE,IDDEP) VALUES
('Epinal', 88)
"; 


$req = "INSERT INTO adresse (IDVILLE, NUMRUE, NOMRUE) VALUES(3, 20, 'Place de l eglise');
INSERT INTO adresse (IDVILLE, NUMRUE, NOMRUE) VALUES(1, 15, 'Rue de la gare');
INSERT INTO adresse (IDVILLE, NUMRUE, NOMRUE) VALUES(2, 3, 'Rue de la gare');
INSERT INTO adresse (IDVILLE, NUMRUE, NOMRUE) VALUES(1, 47, 'Avenue Foch');
INSERT INTO adresse (IDVILLE, NUMRUE, NOMRUE) VALUES(1, 18, 'Place de la republique');
INSERT INTO adresse (IDVILLE, NUMRUE, NOMRUE) VALUES(1, 9, 'Avenue de Boufflers');
INSERT INTO adresse (IDVILLE, NUMRUE, NOMRUE) VALUES(1, 13, 'Rue Michel Ney');
INSERT INTO adresse (IDVILLE, NUMRUE, NOMRUE) VALUES(4, 30, 'Place du chateau');
"; 


$req = "INSERT INTO type (NOMTYPE, ARRETBAIL, DUREEPREAVIS) VALUES
('standard', 3, 36);INSERT INTO type (NOMTYPE, ARRETBAIL, DUREEPREAVIS) VALUES
('meublé vacances', 1, 9);INSERT INTO type (NOMTYPE, ARRETBAIL, DUREEPREAVIS) VALUES
('meublé mixte', 0, 0);
"; 


$req = "INSERT INTO loyer (MONTANT, ANNEE) VALUES
(600, 2014);INSERT INTO loyer (MONTANT, ANNEE) VALUES
(700, 2015);INSERT INTO loyer (MONTANT, ANNEE) VALUES
(500, 2013);INSERT INTO loyer (MONTANT, ANNEE) VALUES
(450, 2015);INSERT INTO loyer (MONTANT, ANNEE) VALUES
(425, 2015);INSERT INTO loyer (MONTANT, ANNEE) VALUES
(430, 2014);INSERT INTO loyer (MONTANT, ANNEE) VALUES
(870, 2015);
"; 

$req = "INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(1, 'Semaine 1');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(2, 'Semaine 2');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(3, 'Semaine 3');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(4, 'Semaine 4');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(5, 'Semaine 5');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(6, 'Semaine 6');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(7, 'Semaine 7');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(8, 'Semaine 8');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(9, 'Semaine 9');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(10, 'Semaine 10');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(11, 'Semaine 11');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(12, 'Semaine 12');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(13, 'Semaine 13');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(14, 'Semaine 14');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(15, 'Semaine 15');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(16, 'Semaine 16');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(17, 'Semaine 17');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(18, 'Semaine 18');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(19, 'Semaine 19');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(20, 'Semaine 20');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(21, 'Semaine 21');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(22, 'Semaine 22');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(23, 'Semaine 23');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(24, 'Semaine 24');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(25, 'Semaine 25');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(26, 'Semaine 26');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(27, 'Semaine 27');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(28, 'Semaine 28');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(29, 'Semaine 29');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(30, 'Semaine 30');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(31, 'Semaine 31');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(32, 'Semaine 32');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(33, 'Semaine 33');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(34, 'Semaine 34');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(35, 'Semaine 35');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(36, 'Semaine 36');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(37, 'Semaine 37');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(38, 'Semaine 38');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(39, 'Semaine 39');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(40, 'Semaine 40');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(41, 'Semaine 41');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(42, 'Semaine 42');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(43, 'Semaine 43');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(44, 'Semaine 44');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(45, 'Semaine 45');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(46, 'Semaine 46');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(47, 'Semaine 47');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(48, 'Semaine 48');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(49, 'Semaine 49');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(50, 'Semaine 50');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(51, 'Semaine 51');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(52, 'Semaine 52');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(53, 'mois 1');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(54, 'mois 2');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(55, 'mois 3');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(56, 'mois 4');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(57, 'mois 5');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(58, 'mois 6');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(59, 'mois 7');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(60, 'mois 8');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(61, 'mois 9');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(62, 'mois 10');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(63, 'mois 11');INSERT INTO plage (IDPLAGE, PLAGE) VALUES
(64, 'mois 12');"; 
$req = "INSERT INTO utilisateur (IDADRESSE, NOM, PRENOM, MAIL, TEL, PASSWORD, ESTOUVERT, IDSYSUSER) VALUES (1,'Alain','Pierre', 'pierre.alain@orange.fr', 0606060606, 'azerty', 1, 1);
INSERT INTO utilisateur (IDADRESSE, NOM, PRENOM, MAIL, TEL, PASSWORD, ESTOUVERT, IDSYSUSER) VALUES (2,'René','Jean', 'rene.jean@orange.fr', 0606060606, 'azerty1234', 1, 1);
INSERT INTO utilisateur (IDADRESSE, NOM, PRENOM, MAIL, TEL, PASSWORD, ESTOUVERT, IDSYSUSER) VALUES (3,'Mouton','Manuel', 'mouton.manuel@orange.fr', 0606060606, 'azerty123', 1, 1);
INSERT INTO utilisateur (IDADRESSE, NOM, PRENOM, MAIL, TEL, PASSWORD, ESTOUVERT, IDSYSUSER) VALUES (4,'Frau','Elise', 'elise.frau@orange.fr', 0606060606, 'azerty12345', 0, 1); 
"; 

$req = "INSERT INTO description (IDAPPARTEMENT, NOMDESCRIPTION, VAL) VALUES (1, 'titre', 'F3 spacieux plein centre');
INSERT INTO description (IDAPPARTEMENT, NOMDESCRIPTION, VAL) VALUES (1, 'description', 'Appartement comportant deux chambres avec une grande cuisine tout équipé (four, plaques, lave-vaisselle). De nombreux rangements disponibles');
INSERT INTO description (IDAPPARTEMENT, NOMDESCRIPTION, VAL) VALUES (2, 'titre', 'F2 proche commerces');
INSERT INTO description (IDAPPARTEMENT, NOMDESCRIPTION, VAL) VALUES (3, 'titre', 'Studio calme exposé sud');        
";    $result = odbc_exec($conn, $req); 

$req = "INSERT INTO appartement (IDTYPE, IDLOYER, IDUTILISATEUR, IDADRESSE, NUMAPPARTEMENT, SURFACE, ESTDISPONIBLE) VALUES (1, 1, 1, 1, 35, 70, 1);
INSERT INTO appartement (IDTYPE, IDLOYER, IDUTILISATEUR, IDADRESSE, NUMAPPARTEMENT, SURFACE, ESTDISPONIBLE) VALUES (1, 2, 2, 2, 7, 104, 1);
INSERT INTO appartement (IDTYPE, IDLOYER, IDUTILISATEUR, IDADRESSE, NUMAPPARTEMENT, SURFACE, ESTDISPONIBLE) VALUES (2, 3, 3, 3, 13, 28, 1);
INSERT INTO appartement (IDTYPE, IDLOYER, IDUTILISATEUR, IDADRESSE, NUMAPPARTEMENT, SURFACE, ESTDISPONIBLE) VALUES (2, 4, 2, 4, 36, 56, 1);
INSERT INTO appartement (IDTYPE, IDLOYER, IDUTILISATEUR, IDADRESSE, NUMAPPARTEMENT, SURFACE, ESTDISPONIBLE) VALUES (3, 5, 2, 4, 35, 45, 0);
"; 

?>